repos:
  - repo: local
    hooks:
      - id: ruff_format
        name: "Ruff format"
        language: system
        files: ^.*\.py$
        entry: "poetry run ruff format ."
        require_serial: true

      - id: ruff_check
        name: "Ruff check"
        language: system
        files: ^.*\.py$
        entry: "poetry run ruff check ."
        # Ruff is fast and checks all files, not just the committed ones
        require_serial: true
